/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Business_logic.Logic_DangNhap;
import java.awt.Color;

/**
 *
 * @author lengo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    Logic_DangNhap lg;

    public Login() {
        initComponents();
        lg = new Logic_DangNhap(this);
        customButton();
    }

    public void customButton() {
        btnDN.colorDefault = new Color(51, 102, 255);
        btnThoat.colorDefault = new Color(51, 102, 255);
        btnSeepass.colorDefault = new Color(51, 102, 255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        roundPanel4 = new library.Swing.RoundPanel();
        name3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnSeepass = new library.Swing.ButtonMenu();
        roundPanel5 = new library.Swing.RoundPanel();
        pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnThoat = new library.Swing.ButtonMenu();
        btnDN = new library.Swing.ButtonMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonMenu2 = new library.Swing.ButtonMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, -1, -1));

        roundPanel4.setBackground(new java.awt.Color(255, 255, 255));

        name3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        name3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundPanel4Layout = new javax.swing.GroupLayout(roundPanel4);
        roundPanel4.setLayout(roundPanel4Layout);
        roundPanel4Layout.setHorizontalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        roundPanel4Layout.setVerticalGroup(
            roundPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(roundPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 240, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên sản phẩm");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        btnSeepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/eye_hide.png"))); // NOI18N
        btnSeepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeepassActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 200, 50, 30));

        roundPanel5.setBackground(new java.awt.Color(255, 255, 255));

        pass.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        javax.swing.GroupLayout roundPanel5Layout = new javax.swing.GroupLayout(roundPanel5);
        roundPanel5.setLayout(roundPanel5Layout);
        roundPanel5Layout.setHorizontalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel5Layout.setVerticalGroup(
            roundPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pass)
                .addContainerGap())
        );

        getContentPane().add(roundPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên sản phẩm");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        btnThoat.setBackground(new java.awt.Color(51, 102, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 90, -1));

        btnDN.setText("Đăng nhập");
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        getContentPane().add(btnDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 90, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 370));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 230, 370));

        buttonMenu2.setText("buttonMenu1");
        getContentPane().add(buttonMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 40, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name3ActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        // TODO add your handling code here:
        lg.loginBtnDn();
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnSeepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeepassActionPerformed
        lg.toggleSeePass();
    }//GEN-LAST:event_btnSeepassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private library.Swing.ButtonMenu btnDN;
    public library.Swing.ButtonMenu btnSeepass;
    private library.Swing.ButtonMenu btnThoat;
    private library.Swing.ButtonMenu buttonMenu2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField name3;
    public javax.swing.JPasswordField pass;
    private library.Swing.RoundPanel roundPanel4;
    private library.Swing.RoundPanel roundPanel5;
    // End of variables declaration//GEN-END:variables
}
